#raw_samples: 'config/sample_info.txt'

human_genome: 'resources/Ref/GCA_000001405.29_GRCh38.p14_genomic_hardMask.fasta'

human_genome_original: 'resources/Ref/GCA_000001405.29_GRCh38.p14_genomic.fna'

targets_per_sample: 'resources/SPOT-BGC__sample-target_info.txt'

targets_per_cohort: 'resources/SPOT-BGC__cohort-target_info.txt'
