# config.yaml 

# user email for notifications

user_email: NO_EMAIL

# files necessary to run the pipeline

human_genome: 'resources/Ref/GCA_000001405.29_GRCh38.p14_genomic_hardMask.fasta'

human_genome_original: 'resources/Ref/GCA_000001405.29_GRCh38.p14_genomic.fna'

targets_per_sample: 'resources/SPOT-BGC__sample-target_info.txt'

targets_per_cohort: 'resources/SPOT-BGC__cohort-target_info.txt'

# thread settings that users may want to alter

threads_trimming: 5

threads_bowtie_index: 5

threads_bowtie: 10

threads_bbnorm: 10

threads_metaspades: 20

threads_megahit: 20

threads_kraken: 10

threads_metabat: 10

threads_checkm: 10

threads_gecco: 5

threads_antismash: 5

# additional program settings

metabat_bin_size: 10000

antismash_sample_process_num: 1

antismash_cohort_process_num: 4
